### ISSUE TITLE
🎥 [FEATURE] Synchronized Video Player with Transcript Navigation

### ISSUE THREAD

**Issue by bazgreen** [bazgreen/video-transcriber#26]
# 🎥 [FEATURE] Synchronized Video Player with Transcript Navigation

## 🎯 Problem Statement

Currently, users have **static transcripts** and **video files separately**, creating a fragmented experience where:
- Users cannot easily navigate between transcript segments and video content
- Video review requires manual seeking without transcript context
- Educational content lacks interactive audio-visual-text synchronization
- Professional content review is inefficient and time-consuming

## 💡 Proposed Solution

Implement a **synchronized video player** that allows bidirectional navigation between video content and transcript segments, transforming the static transcript into an interactive media experience.

#### 1. **Synchronized Video Player**
- HTML5 video player embedded in results page
- Automatic video file serving from session storage
- Progress bar with chapter markers based on content analysis
- Responsive design for desktop and mobile devices

#### 2. **Bidirectional Navigation**
- **Transcript → Video**: Click any transcript segment to jump to exact video time
- **Video → Transcript**: Video playback auto-highlights current transcript segment
- **Smooth Seeking**: Precise timestamp synchronization with visual feedback

#### 3. **Smart Chapter Generation**
- Automatic chapter detection based on keyword density clusters
- Visual chapter markers on video timeline
- Quick navigation to content sections (questions, emphasis cues, keywords)
- Chapter titles generated from detected content themes

#### 4. **Enhanced User Experience**
- Playback speed controls (0.5x - 2x) with maintained transcript sync
- Keyboard shortcuts for common navigation actions
- Mobile-optimized touch controls and gesture support
- Loading states and error handling for video playback

#### Backend Changes
```python
# New route in src/routes/api.py
@api_bp.route('/video/<session_id>')
def serve_video(session_id):
    """Serve original video file for synchronized playback"""
    if not is_valid_session_id(session_id):
        return jsonify({'error': 'Invalid session ID'}), 400
    
    session_dir = os.path.join(app_config.RESULTS_FOLDER, session_id)
    
    # Find original video file in session directory
    metadata_path = os.path.join(session_dir, 'metadata.json')
    if not os.path.exists(metadata_path):
        return jsonify({'error': 'Session metadata not found'}), 404
        
    with open(metadata_path, 'r') as f:
        metadata = json.load(f)
    
    original_filename = metadata.get('original_filename')
    if not original_filename:
        return jsonify({'error': 'Original video file reference not found'}), 404
    
    # Look for video file by original name or pattern
    video_extensions = ['mp4', 'avi', 'mov', 'mkv', 'webm', 'flv', 'wmv', 'm4v']
    video_files = []
    
    for ext in video_extensions:
        pattern = os.path.join(session_dir, f"*.{ext}")
        video_files.extend(glob.glob(pattern))
    
    if not video_files:
        return jsonify({'error': 'Video file not found in session'}), 404
        
    video_path = video_files[0]  # Use first found video file
    
    # Security check
    if not is_safe_path(video_path, session_dir):
        return jsonify({'error': 'Invalid file path'}), 403
    
    return send_file(video_path, as_attachment=False, 
                    mimetype='video/mp4',
                    conditional=True)  # Enable range requests for seeking

@api_bp.route('/video/<session_id>/metadata')
def get_video_metadata(session_id):
    """Get video metadata for player initialization"""
    if not is_valid_session_id(session_id):
        return jsonify({'error': 'Invalid session ID'}), 400
    
    session_dir = os.path.join(app_config.RESULTS_FOLDER, session_id)
    analysis_path = os.path.join(session_dir, 'analysis.json')
    
    if not os.path.exists(analysis_path):
        return jsonify({'error': 'Analysis data not found'}), 404
    
    with open(analysis_path, 'r') as f:
        analysis = json.load(f)
    
    # Generate chapter markers from content analysis
    chapters = generate_video_chapters(analysis)
    
    return jsonify({
        'success': True,
        'chapters': chapters,
        'total_duration': analysis.get('total_duration', 0),
        'segments_count': len(analysis.get('segments', [])),
        'keywords': analysis.get('keyword_matches', []),
        'questions': analysis.get('questions', []),
        'emphasis_cues': analysis.get('emphasis_cues', [])
    })
```

#### Utility Functions
```python
# Add to src/utils/__init__.py or new src/utils/video_utils.py
def generate_video_chapters(analysis_data):
    """Generate chapter markers from content analysis"""
    chapters = []
    segments = analysis_data.get('segments', [])
    
    if not segments:
        return chapters
    
    # Basic chapter: every 2 minutes or at question boundaries
    chapter_interval = 120  # 2 minutes
    current_time = 0
    
    for segment in segments:
        segment_start = float(segment.get('start', 0))
        
        # Create chapter at intervals or at questions
        if (segment_start - current_time >= chapter_interval or 
            any(q.get('timestamp_seconds', 0) == segment_start 
                for q in analysis_data.get('questions', []))):
            
            # Generate chapter title from nearby keywords or content
            title = generate_chapter_title(segment, analysis_data)
            
            chapters.append({
                'time': segment_start,
                'title': title,
                'keywords': get_nearby_keywords(segment_start, analysis_data)
            })
            current_time = segment_start
    
    return chapters

def generate_chapter_title(segment, analysis_data):
    """Generate meaningful chapter title from segment content"""
    text = segment.get('text', '').strip()
    
    # Look for questions near this timestamp
    questions = analysis_data.get('questions', [])
    nearby_question = next((q for q in questions 
                           if abs(q.get('timestamp_seconds', 0) - 
                                 float(segment.get('start', 0))) < 30), None)
    
    if nearby_question:
        return f"Q: {nearby_question['text'][:50]}..."
    
    # Look for keyword clusters
    keywords = analysis_data.get('keyword_matches', [])
    if keywords:
        return f"Content: {text[:50]}..."
    
    # Default chapter naming
    minutes = int(float(segment.get('start', 0)) // 60)
    seconds = int(float(segment.get('start', 0)) % 60)
    return f"Chapter {minutes:02d}:{seconds:02d}"
```

#### Template Updates
```html
<!-- Add to data/templates/results.html after session-info section -->
<div class="video-transcript-container">
    <div class="video-player-section">
        <div class="video-player-wrapper">
            <video id="syncedPlayer" 
                   controls 
                   preload="metadata"
                   crossorigin="anonymous">
                <source src="/api/video/{{ session_id }}" type="video/mp4">
                <p>Your browser does not support the video element.</p>
            </video>
            
            <div class="video-controls-overlay">
                <div class="chapter-markers" id="chapterMarkers"></div>
                <div class="progress-indicators">
                    <div class="keywords-timeline" id="keywordsTimeline"></div>
                    <div class="questions-timeline" id="questionsTimeline"></div>
                </div>
            </div>
        </div>
        
        <div class="video-metadata">
            <div class="playback-controls">
                <label for="playbackSpeed">Speed:</label>
                <select id="playbackSpeed">
                    <option value="0.5">0.5x</option>
                    <option value="0.75">0.75x</option>
                    <option value="1" selected>1x</option>
                    <option value="1.25">1.25x</option>
                    <option value="1.5">1.5x</option>
                    <option value="2">2x</option>
                </select>
            </div>
            
            <div class="quick-navigation">
                <button class="nav-btn" data-action="prev-question">⏮️ Prev Question</button>
                <button class="nav-btn" data-action="next-question">⏭️ Next Question</button>
                <button class="nav-btn" data-action="prev-keyword">🔍 Prev Keyword</button>
                <button class="nav-btn" data-action="next-keyword">🔍 Next Keyword</button>
            </div>
        </div>
    </div>
    
    <div class="synchronized-transcript-section">
        <div class="transcript-header">
            <h3>📋 Interactive Transcript</h3>
            <div class="transcript-controls">
                <input type="search" id="transcriptSearch" placeholder="Search transcript...">
                <button id="highlightKeywords">🎯 Highlight Keywords</button>
                <button id="showTimestamps">⏰ Show Timestamps</button>
            </div>
        </div>
        
        <div class="transcript-content" id="transcriptContent">
            <!-- Transcript segments will be populated here -->
        </div>
    </div>
</div>
```

#### CSS Styling
```css
/* Add to data/templates/results.html <style> section */
.video-transcript-container {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 30px;
    margin-bottom: 30px;
}

@media (max-width: 1024px) {
    .video-transcript-container {
        grid-template-columns: 1fr;
    }
}

.video-player-section {
    background: white;
    padding: 20px;
    border-radius: 12px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
}

.video-player-wrapper {
    position: relative;
    margin-bottom: 15px;
}

#syncedPlayer {
    width: 100%;
    height: auto;
    border-radius: 8px;
    background: #000;
}

.video-controls-overlay {
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    pointer-events: none;
}

.chapter-markers {
    height: 4px;
    background: rgba(255, 255, 255, 0.3);
    border-radius: 2px;
    margin: 2px 10px;
    position: relative;
}

.chapter-marker {
    position: absolute;
    width: 2px;
    height: 4px;
    background: #667eea;
    cursor: pointer;
    pointer-events: all;
}

.chapter-marker:hover::after {
    content: attr(data-title);
    position: absolute;
    bottom: 8px;
    left: 50%;
    transform: translateX(-50%);
    background: rgba(0, 0, 0, 0.8);
    color: white;
    padding: 4px 8px;
    border-radius: 4px;
    font-size: 12px;
    white-space: nowrap;
    z-index: 10;
}

.progress-indicators {
    height: 6px;
    margin: 2px 10px;
    display: flex;
    flex-direction: column;
    gap: 1px;
}

.keywords-timeline, .questions-timeline {
    height: 2px;
    background: rgba(255, 255, 255, 0.2);
    border-radius: 1px;
    position: relative;
}

.timeline-indicator {
    position: absolute;
    width: 4px;
    height: 2px;
    border-radius: 1px;
    cursor: pointer;
    pointer-events: all;
}

.keyword-indicator {
    background: #48bb78;
}

.question-indicator {
    background: #ed8936;
}

.video-metadata {
    display: flex;
    justify-content: space-between;
    align-items: center;
    flex-wrap: wrap;
    gap: 15px;
}

.playback-controls select {
    margin-left: 8px;
    padding: 4px 8px;
    border: 1px solid #ddd;
    border-radius: 4px;
}

.quick-navigation {
    display: flex;
    gap: 8px;
    flex-wrap: wrap;
}

.nav-btn {
    background: #f7fafc;
    border: 1px solid #e2e8f0;
    padding: 6px 12px;
    border-radius: 6px;
    cursor: pointer;
    font-size: 12px;
    transition: all 0.2s ease;
}

.nav-btn:hover {
    background: #edf2f7;
    border-color: #cbd5e0;
}

.synchronized-transcript-section {
    background: white;
    padding: 20px;
    border-radius: 12px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    display: flex;
    flex-direction: column;
}

.transcript-header {
    margin-bottom: 15px;
    padding-bottom: 15px;
    border-bottom: 1px solid #f0f0f0;
}

.transcript-controls {
    display: flex;
    gap: 10px;
    align-items: center;
    flex-wrap: wrap;
    margin-top: 10px;
}

#transcriptSearch {
    flex: 1;
    min-width: 200px;
    padding: 8px 12px;
    border: 1px solid #ddd;
    border-radius: 6px;
}

.transcript-content {
    max-height: 400px;
    overflow-y: auto;
    line-height: 1.6;
}

.transcript-segment {
    padding: 8px 12px;
    margin: 4px 0;
    border-radius: 6px;
    cursor: pointer;
    transition: all 0.2s ease;
    border-left: 3px solid transparent;
}

.transcript-segment:hover {
    background: #f7fafc;
    border-left-color: #667eea;
}

.transcript-segment.active {
    background: #edf2f7;
    border-left-color: #667eea;
    box-shadow: 0 2px 4px rgba(102, 126, 234, 0.1);
}

.segment-timestamp {
    display: inline-block;
    background: #667eea;
    color: white;
    padding: 2px 6px;
    border-radius: 3px;
    font-size: 11px;
    margin-right: 8px;
    font-weight: 500;
}

.segment-text {
    display: inline;
}

.keyword-highlight {
    background: #fef5e7;
    color: #744210;
    padding: 1px 3px;
    border-radius: 2px;
    font-weight: 500;
}

.question-highlight {
    background: #fed7d7;
    color: #742a2a;
    padding: 1px 3px;
    border-radius: 2px;
    font-weight: 500;
}

.emphasis-highlight {
    background: #e6fffa;
    color: #234e52;
    padding: 1px 3px;
    border-radius: 2px;
    font-weight: 500;
}
```

### Phase 3: JavaScript Synchronization Engine (2-3 days)

```javascript
// Add to data/templates/results.html <script> section
class VideoTranscriptSync {
    constructor(sessionId) {
        this.sessionId = sessionId;
        this.video = document.getElementById('syncedPlayer');
        this.transcriptContent = document.getElementById('transcriptContent');
        this.segments = [];
        this.chapters = [];
        this.keywords = [];
        this.questions = [];
        this.currentSegmentIndex = -1;
        this.isUserSeeking = false;
        
        this.init();
    }
    
    async init() {
        try {
            // Load video metadata and transcript data
            await this.loadMetadata();
            await this.loadTranscriptData();
            
            // Initialize UI components
            this.setupVideoPlayer();
            this.setupTranscriptNavigation();
            this.setupChapterMarkers();
            this.setupTimelineIndicators();
            this.setupKeyboardShortcuts();
            this.setupMobileOptimizations();
            
            console.log('VideoTranscriptSync initialized successfully');
        } catch (error) {
            console.error('Failed to initialize VideoTranscriptSync:', error);
            this.showError('Failed to load video synchronization features');
        }
    }
    
    async loadMetadata() {
        const response = await fetch(`/api/video/${this.sessionId}/metadata`);
        if (!response.ok) {
            throw new Error('Failed to load video metadata');
        }
        
        const data = await response.json();
        this.chapters = data.chapters || [];
        this.keywords = data.keywords || [];
        this.questions = data.questions || [];
        this.totalDuration = data.total_duration || 0;
    }
    
    async loadTranscriptData() {
        // Load transcript segments from the analysis data
        const response = await fetch(`/download/${this.sessionId}/analysis.json`);
        if (!response.ok) {
            throw new Error('Failed to load transcript data');
        }
        
        const analysisData = await response.json();
        this.segments = analysisData.segments || [];
        
        // Render transcript in the UI
        this.renderTranscript();
    }
    
    setupVideoPlayer() {
        if (!this.video) {
            console.error('Video element not found');
            return;
        }
        
        // Video event listeners
        this.video.addEventListener('loadedmetadata', () => {
            console.log('Video metadata loaded');
            this.updateChapterMarkers();
            this.updateTimelineIndicators();
        });
        
        this.video.addEventListener('timeupdate', () => {
            if (!this.isUserSeeking) {
                this.updateCurrentSegment();
            }
        });
        
        this.video.addEventListener('seeking', () => {
            this.isUserSeeking = true;
        });
        
        this.video.addEventListener('seeked', () => {
            this.isUserSeeking = false;
            this.updateCurrentSegment();
        });
        
        this.video.addEventListener('error', (e) => {
            console.error('Video playback error:', e);
            this.showError('Video playback failed. Please check your connection.');
        });
        
        // Playback speed control
        const speedControl = document.getElementById('playbackSpeed');
        if (speedControl) {
            speedControl.addEventListener('change', (e) => {
                this.video.playbackRate = parseFloat(e.target.value);
            });
        }
        
        // Quick navigation buttons
        document.querySelectorAll('.nav-btn').forEach(btn => {
            btn.addEventListener('click', (e) => {
                const action = e.target.dataset.action;
                this.handleQuickNavigation(action);
            });
        });
    }
    
    setupTranscriptNavigation() {
        // Search functionality
        const searchInput = document.getElementById('transcriptSearch');
        if (searchInput) {
            searchInput.addEventListener('input', (e) => {
                this.searchTranscript(e.target.value);
            });
        }
        
        // Highlight toggles
        const highlightKeywords = document.getElementById('highlightKeywords');
        if (highlightKeywords) {
            highlightKeywords.addEventListener('click', () => {
                this.toggleKeywordHighlights();
            });
        }
        
        const showTimestamps = document.getElementById('showTimestamps');
        if (showTimestamps) {
            showTimestamps.addEventListener('click', () => {
                this.toggleTimestampVisibility();
            });
        }
    }
    
    renderTranscript() {
        if (!this.transcriptContent || !this.segments.length) {
            this.transcriptContent.innerHTML = '<p class="no-content">No transcript data available</p>';
            return;
        }
        
        let html = '';
        this.segments.forEach((segment, index) => {
            const startTime = parseFloat(segment.start || 0);
            const timestamp = this.formatTimestamp(startTime);
            
            html += `
                <div class="transcript-segment" 
                     data-index="${index}" 
                     data-start="${startTime}"
                     data-end="${parseFloat(segment.end || 0)}">
                    <span class="segment-timestamp">${timestamp}</span>
                    <span class="segment-text">${this.highlightContent(segment.text || '')}</span>
                </div>
            `;
        });
        
        this.transcriptContent.innerHTML = html;
        
        // Add click handlers to segments
        document.querySelectorAll('.transcript-segment').forEach(segment => {
            segment.addEventListener('click', (e) => {
                const startTime = parseFloat(e.currentTarget.dataset.start);
                this.seekToTime(startTime);
            });
        });
    }
    
    highlightContent(text) {
        let highlightedText = text;
        
        // Highlight keywords
        this.keywords.forEach(keyword => {
            const regex = new RegExp(`\\b(${keyword.keyword})\\b`, 'gi');
            highlightedText = highlightedText.replace(regex, 
                '<span class="keyword-highlight">$1</span>');
        });
        
        // Highlight questions (simple heuristic)
        if (text.includes('?')) {
            highlightedText = highlightedText.replace(/([^.!?]*\?)/g, 
                '<span class="question-highlight">$1</span>');
        }
        
        // Highlight emphasis cues (words in caps, repeated words, etc.)
        highlightedText = highlightedText.replace(/\b([A-Z]{2,})\b/g, 
            '<span class="emphasis-highlight">$1</span>');
        
        return highlightedText;
    }
    
    updateCurrentSegment() {
        if (!this.video || !this.segments.length) return;
        
        const currentTime = this.video.currentTime;
        const newSegmentIndex = this.segments.findIndex(segment => {
            const start = parseFloat(segment.start || 0);
            const end = parseFloat(segment.end || 0);
            return currentTime >= start && currentTime <= end;
        });
        
        if (newSegmentIndex !== this.currentSegmentIndex && newSegmentIndex !== -1) {
            // Remove previous highlight
            if (this.currentSegmentIndex !== -1) {
                const prevSegment = document.querySelector(
                    `.transcript-segment[data-index="${this.currentSegmentIndex}"]`
                );
                if (prevSegment) {
                    prevSegment.classList.remove('active');
                }
            }
            
            // Add new highlight
            this.currentSegmentIndex = newSegmentIndex;
            const currentSegment = document.querySelector(
                `.transcript-segment[data-index="${this.currentSegmentIndex}"]`
            );
            if (currentSegment) {
                currentSegment.classList.add('active');
                
                // Scroll to current segment if it's not visible
                const containerRect = this.transcriptContent.getBoundingClientRect();
                const segmentRect = currentSegment.getBoundingClientRect();
                
                if (segmentRect.top < containerRect.top || 
                    segmentRect.bottom > containerRect.bottom) {
                    currentSegment.scrollIntoView({ 
                        behavior: 'smooth', 
                        block: 'center' 
                    });
                }
            }
        }
    }
    
    seekToTime(time) {
        if (this.video) {
            this.video.currentTime = time;
            if (this.video.paused) {
                this.video.play().catch(e => {
                    console.log('Autoplay prevented:', e);
                });
            }
        }
    }
    
    setupChapterMarkers() {
        const markersContainer = document.getElementById('chapterMarkers');
        if (!markersContainer || !this.chapters.length || !this.totalDuration) return;
        
        this.chapters.forEach(chapter => {
            const position = (chapter.time / this.totalDuration) * 100;
            const marker = document.createElement('div');
            marker.className = 'chapter-marker';
            marker.style.left = `${position}%`;
            marker.dataset.time = chapter.time;
            marker.dataset.title = chapter.title;
            
            marker.addEventListener('click', () => {
                this.seekToTime(chapter.time);
            });
            
            markersContainer.appendChild(marker);
        });
    }
    
    setupTimelineIndicators() {
        this.setupKeywordIndicators();
        this.setupQuestionIndicators();
    }
    
    setupKeywordIndicators() {
        const timeline = document.getElementById('keywordsTimeline');
        if (!timeline || !this.keywords.length || !this.totalDuration) return;
        
        this.keywords.forEach(keyword => {
            keyword.instances?.forEach(instance => {
                const position = (instance.timestamp / this.totalDuration) * 100;
                const indicator = document.createElement('div');
                indicator.className = 'timeline-indicator keyword-indicator';
                indicator.style.left = `${position}%`;
                indicator.title = `${keyword.keyword} at ${this.formatTimestamp(instance.timestamp)}`;
                
                indicator.addEventListener('click', () => {
                    this.seekToTime(instance.timestamp);
                });
                
                timeline.appendChild(indicator);
            });
        });
    }
    
    setupQuestionIndicators() {
        const timeline = document.getElementById('questionsTimeline');
        if (!timeline || !this.questions.length || !this.totalDuration) return;
        
        this.questions.forEach(question => {
            const timestamp = question.timestamp_seconds || 0;
            const position = (timestamp / this.totalDuration) * 100;
            const indicator = document.createElement('div');
            indicator.className = 'timeline-indicator question-indicator';
            indicator.style.left = `${position}%`;
            indicator.title = `Question: ${question.text.substring(0, 50)}...`;
            
            indicator.addEventListener('click', () => {
                this.seekToTime(timestamp);
            });
            
            timeline.appendChild(indicator);
        });
    }
    
    handleQuickNavigation(action) {
        const currentTime = this.video?.currentTime || 0;
        
        switch (action) {
            case 'prev-question':
                this.navigateToQuestion(-1, currentTime);
                break;
            case 'next-question':
                this.navigateToQuestion(1, currentTime);
                break;
            case 'prev-keyword':
                this.navigateToKeyword(-1, currentTime);
                break;
            case 'next-keyword':
                this.navigateToKeyword(1, currentTime);
                break;
        }
    }
    
    navigateToQuestion(direction, currentTime) {
        const questions = this.questions
            .map(q => ({ ...q, time: q.timestamp_seconds || 0 }))
            .sort((a, b) => a.time - b.time);
        
        let targetIndex = -1;
        
        if (direction > 0) {
            // Next question
            targetIndex = questions.findIndex(q => q.time > currentTime + 1);
        } else {
            // Previous question
            for (let i = questions.length - 1; i >= 0; i--) {
                if (questions[i].time < currentTime - 1) {
                    targetIndex = i;
                    break;
                }
            }
        }
        
        if (targetIndex !== -1) {
            this.seekToTime(questions[targetIndex].time);
        }
    }
    
    navigateToKeyword(direction, currentTime) {
        const keywordInstances = [];
        this.keywords.forEach(keyword => {
            keyword.instances?.forEach(instance => {
                keywordInstances.push({ ...instance, keyword: keyword.keyword });
            });
        });
        
        keywordInstances.sort((a, b) => a.timestamp - b.timestamp);
        
        let targetIndex = -1;
        
        if (direction > 0) {
            // Next keyword
            targetIndex = keywordInstances.findIndex(k => k.timestamp > currentTime + 1);
        } else {
            // Previous keyword
            for (let i = keywordInstances.length - 1; i >= 0; i--) {
                if (keywordInstances[i].timestamp < currentTime - 1) {
                    targetIndex = i;
                    break;
                }
            }
        }
        
        if (targetIndex !== -1) {
            this.seekToTime(keywordInstances[targetIndex].timestamp);
        }
    }
    
    searchTranscript(query) {
        if (!query.trim()) {
            // Clear search highlighting
            document.querySelectorAll('.transcript-segment').forEach(segment => {
                segment.style.display = 'block';
                segment.classList.remove('search-highlight');
            });
            return;
        }
        
        const searchRegex = new RegExp(query, 'gi');
        let hasResults = false;
        
        document.querySelectorAll('.transcript-segment').forEach(segment => {
            const text = segment.querySelector('.segment-text').textContent;
            
            if (searchRegex.test(text)) {
                segment.style.display = 'block';
                segment.classList.add('search-highlight');
                hasResults = true;
            } else {
                segment.style.display = 'none';
                segment.classList.remove('search-highlight');
            }
        });
        
        if (!hasResults) {
            this.showMessage('No results found for your search.', 'info');
        }
    }
    
    toggleKeywordHighlights() {
        const isActive = document.body.classList.toggle('keywords-highlighted');
        const btn = document.getElementById('highlightKeywords');
        if (btn) {
            btn.textContent = isActive ? '🎯 Hide Keywords' : '🎯 Highlight Keywords';
            btn.style.background = isActive ? '#667eea' : '';
            btn.style.color = isActive ? 'white' : '';
        }
    }
    
    toggleTimestampVisibility() {
        const isVisible = document.body.classList.toggle('timestamps-visible');
        const btn = document.getElementById('showTimestamps');
        if (btn) {
            btn.textContent = isVisible ? '⏰ Hide Timestamps' : '⏰ Show Timestamps';
            btn.style.background = isVisible ? '#667eea' : '';
            btn.style.color = isVisible ? 'white' : '';
        }
    }
    
    setupKeyboardShortcuts() {
        document.addEventListener('keydown', (e) => {
            // Only handle shortcuts when video is focused or when not in input fields
            if (e.target.tagName === 'INPUT' || e.target.tagName === 'TEXTAREA') {
                return;
            }
            
            switch (e.key) {
                case ' ':
                    e.preventDefault();
                    this.video?.paused ? this.video.play() : this.video.pause();
                    break;
                case 'ArrowLeft':
                    e.preventDefault();
                    if (this.video) this.video.currentTime -= 10;
                    break;
                case 'ArrowRight':
                    e.preventDefault();
                    if (this.video) this.video.currentTime += 10;
                    break;
                case 'q':
                    e.preventDefault();
                    this.handleQuickNavigation('next-question');
                    break;
                case 'Q':
                    e.preventDefault();
                    this.handleQuickNavigation('prev-question');
                    break;
                case 'k':
                    e.preventDefault();
                    this.handleQuickNavigation('next-keyword');
                    break;
                case 'K':
                    e.preventDefault();
                    this.handleQuickNavigation('prev-keyword');
                    break;
            }
        });
    }
    
    setupMobileOptimizations() {
        // Touch gesture support for mobile devices
        if ('ontouchstart' in window) {
            let touchStartX = 0;
            let touchStartY = 0;
            
            this.transcriptContent.addEventListener('touchstart', (e) => {
                touchStartX = e.touches[0].clientX;
                touchStartY = e.touches[0].clientY;
            });
            
            this.transcriptContent.addEventListener('touchend', (e) => {
                const touchEndX = e.changedTouches[0].clientX;
                const touchEndY = e.changedTouches[0].clientY;
                
                const deltaX = touchEndX - touchStartX;
                const deltaY = touchEndY - touchStartY;
                
                // Horizontal swipe gestures for navigation
                if (Math.abs(deltaX) > Math.abs(deltaY) && Math.abs(deltaX) > 50) {
                    if (deltaX > 0) {
                        // Swipe right - previous question
                        this.handleQuickNavigation('prev-question');
                    } else {
                        // Swipe left - next question
                        this.handleQuickNavigation('next-question');
                    }
                }
            });
        }
    }
    
    formatTimestamp(seconds) {
        const hours = Math.floor(seconds / 3600);
        const minutes = Math.floor((seconds % 3600) / 60);
        const secs = Math.floor(seconds % 60);
        
        if (hours > 0) {
            return `${hours:02d}:${minutes:02d}:${secs:02d}`;
        }
        return `${minutes:02d}:${secs:02d}`;
    }
    
    showError(message) {
        this.showMessage(message, 'error');
    }
    
    showMessage(message, type = 'info') {
        // Create a toast notification
        const toast = document.createElement('div');
        toast.className = `toast toast-${type}`;
        toast.textContent = message;
        
        Object.assign(toast.style, {
            position: 'fixed',
            top: '20px',
            right: '20px',
            background: type === 'error' ? '#e53e3e' : '#4299e1',
            color: 'white',
            padding: '12px 20px',
            borderRadius: '6px',
            zIndex: '1000',
            maxWidth: '300px',
            boxShadow: '0 4px 12px rgba(0, 0, 0, 0.2)'
        });
        
        document.body.appendChild(toast);
        
        setTimeout(() => {
            toast.remove();
        }, 5000);
    }
}

// Initialize when DOM is ready
document.addEventListener('DOMContentLoaded', function() {
    // Only initialize if we're on a results page with video support
    if (document.getElementById('syncedPlayer')) {
        const sessionId = '{{ session_id }}';
        window.videoSync = new VideoTranscriptSync(sessionId);
    }
});
```

#### Mobile Optimizations
- Touch-friendly controls with larger hit targets
- Gesture support for navigation (swipe for next/prev)
- Responsive video player sizing
- Mobile-specific UI adaptations

#### Performance Optimizations
- Lazy loading of video content
- Efficient segment highlighting algorithms
- Memory management for long transcripts
- Optimized seek performance

#### Accessibility Features
- Screen reader compatibility
- Keyboard navigation support
- High contrast mode support
- ARIA labels and roles

### Core Functionality
- [ ] **Video Playback**: Original video files load and play correctly in HTML5 player
- [ ] **Transcript Sync**: Clicking transcript segments seeks video to exact timestamp (±1 second accuracy)
- [ ] **Active Highlighting**: Video playback highlights current transcript segment automatically
- [ ] **Chapter Navigation**: Auto-generated chapters allow quick navigation to content sections
- [ ] **Timeline Indicators**: Keywords and questions visible as clickable markers on video timeline

### User Experience
- [ ] **Search Functionality**: Transcript search filters and highlights matching segments
- [ ] **Speed Controls**: Playback speed adjustment (0.5x - 2x) maintains transcript synchronization
- [ ] **Quick Navigation**: Prev/Next buttons for questions and keywords work accurately
- [ ] **Mobile Responsive**: Interface adapts to mobile screens with touch-friendly controls
- [ ] **Loading States**: Appropriate loading indicators and error handling for video/data

### Performance
- [ ] **Fast Loading**: Video metadata loads within 2 seconds
- [ ] **Smooth Seeking**: Video seeking responds within 500ms of transcript clicks
- [ ] **Memory Efficient**: No memory leaks during extended playback sessions
- [ ] **Network Optimized**: Video served with range request support for efficient seeking
- [ ] **Responsive UI**: Interface remains responsive during video playback and seeking

### Technical Requirements
- [ ] **Browser Compatibility**: Works in Chrome 90+, Firefox 88+, Safari 14+, Edge 90+
- [ ] **Video Formats**: Supports all currently processed video formats (MP4, AVI, MOV, etc.)
- [ ] **Security**: Video serving includes proper access controls and path validation
- [ ] **Error Recovery**: Graceful handling of missing videos, network issues, and playback errors
- [ ] **Accessibility**: WCAG 2.1 AA compliance with screen reader support

### Advanced Features (Future Phases)
- [ ] **Keyboard Shortcuts**: Space (play/pause), arrows (seek), Q/K (navigate questions/keywords)
- [ ] **Chapter Auto-generation**: Smart chapter detection based on content analysis
- [ ] **Gesture Support**: Touch gestures for mobile navigation
- [ ] **Export Integration**: Chapter markers included in SRT/VTT exports
- [ ] **Analytics**: Track user interaction patterns with video navigation

## 🏷️ Labels
`enhancement`, `video`, `ui/ux`, `high-priority`

### User Engagement
- **Transcript Interaction**: 300-500% increase in transcript click-through rate
- **Session Duration**: 40-60% increase in time spent reviewing transcripts
- **Feature Adoption**: >70% of users interact with video navigation within first session

### Technical Performance
- **Load Time**: Video metadata loads in <2 seconds
- **Sync Accuracy**: Timestamp synchronization accurate within 1 second
- **Error Rate**: <5% video playback failures
- **Mobile Usage**: >30% of video navigation occurs on mobile devices

### Business Impact
- **User Satisfaction**: Improved NPS score for transcript usability
- **Feature Differentiation**: Unique selling point vs. competitors
- **Educational Value**: Enhanced learning outcomes for educational users
- **Professional Efficiency**: 50-70% reduction in content review time

### Technical Dependencies
- HTML5 video support in target browsers
- Range request support for video seeking
- Existing transcript timestamp accuracy
- Session storage and metadata system

### Development Dependencies
- Video serving infrastructure implementation
- Frontend JavaScript framework (vanilla JS sufficient)
- CSS Grid/Flexbox for responsive layout
- Testing framework for cross-browser validation

### Technical Risks
- **Video Compatibility**: Fallback for unsupported video formats
- **Network Issues**: Graceful degradation for slow connections
- **Browser Support**: Progressive enhancement for older browsers
- **Mobile Performance**: Optimized video loading for mobile devices

### User Experience Risks
- **Learning Curve**: Intuitive interface design with tooltips/hints
- **Feature Discovery**: Clear visual cues for interactive elements
- **Performance Impact**: Efficient algorithms to maintain responsiveness
- **Accessibility**: Comprehensive keyboard and screen reader support

## 🎯 Priority: HIGH

This feature represents a significant value proposition upgrade, transforming the application from a "transcription tool" into an "interactive video analysis platform." It leverages existing robust infrastructure while providing immediate, tangible user value.

## 📅 Estimated Timeline: 1-2 weeks

- Phase 1 (Video Infrastructure): 2-3 days
- Phase 2 (UI Implementation): 1-2 days  
- Phase 3 (JavaScript Engine): 2-3 days
- Phase 4 (Polish & Testing): 2-3 days

## 👥 Stakeholders
- End users (students, educators, professionals)
- Development team
- QA/Testing team
- UI/UX design review
